/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redireciona para /openapi, onde se escolhe o estilo de documentação. */
        get: operations["inicio__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cotacoes/{cotacao_id}/contratar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Contrata uma cotação
         * @description Contrata a cotação escolhida: o pedido passa de cotado para contratado.<br/><br/>Grava no pedido a cotação contratada e a data prometida ao cliente, que<br/>depois serve para identificar atrasos.
         */
        put: operations["cotacoes_contratar_cotacoes__int_cotacao_id__contratar_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modalidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as modalidades de frete
         * @description Devolve as modalidades (econômico, padrão, expresso) e seus ajustes.
         */
        get: operations["tarifas_listar_modalidades_modalidades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/painel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores do painel
         * @description Consolida contagem por status, frete médio (geral e por região), pedidos<br/>atrasados e prazo médio das cotações contratadas.<br/><br/>"Frete" aqui é sempre o valor da cotação contratada; pedidos cancelados<br/>ficam fora das médias.
         */
        get: operations["painel_painel_painel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista pedidos com filtros e paginação
         * @description Lista pedidos do mais recente para o mais antigo.<br/><br/>Filtros opcionais: status, uf e busca livre `q` (nome do cliente, cidade ou<br/>id externo). A paginação devolve também o total e o número de páginas.
         */
        get: operations["pedidos_listar_pedidos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importa pedidos da DummyJSON
         * @description Importa um lote de carts da DummyJSON como pedidos.<br/><br/>Pedidos já existentes são ignorados (idempotência por id_externo). Cada<br/>pedido novo recebe um endereço real confirmado na BrasilAPI.
         */
        post: operations["pedidos_importar_pedidos_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha um pedido
         * @description Devolve o pedido com itens, cotações e movimentações (linha do tempo).
         */
        get: operations["pedidos_detalhar_pedidos__int_pedido_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancela o pedido
         * @description Cancela o pedido (exclusão lógica: o registro e o histórico são mantidos).<br/><br/>Só é permitido antes de em_transito; depois disso retorna 409.
         */
        delete: operations["pedidos_cancelar_pedidos__int_pedido_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}/cotacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera cotações de frete para o pedido
         * @description Calcula uma cotação por modalidade ativa e move o pedido de recebido para cotado.<br/><br/>Um pedido já cotado pode ser cotado de novo (por exemplo, após editar a<br/>tabela de tarifas): as cotações anteriores não contratadas são substituídas.
         */
        post: operations["pedidos_cotar_pedidos__int_pedido_id__cotacoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Avança o status do pedido
         * @description Muda o status conforme a máquina de estados (ex.: contratado → em_transito).<br/><br/>Transições fora das regras retornam 409. Para cotar, contratar ou cancelar<br/>use as rotas específicas, que também gravam cotações e datas.
         */
        put: operations["pedidos_atualizar_status_pedidos__int_pedido_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tarifas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista a tabela de tarifas
         * @description Devolve todas as tarifas ordenadas por faixa de peso e de distância.
         */
        get: operations["tarifas_listar_tarifas_tarifas_get"];
        put?: never;
        /**
         * Cria uma tarifa
         * @description Cria uma nova célula na tabela; a combinação peso × distância deve ser única.
         */
        post: operations["tarifas_criar_tarifa_tarifas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tarifas/{tarifa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma tarifa
         * @description Devolve uma tarifa pelo id.
         */
        get: operations["tarifas_detalhar_tarifa_tarifas__int_tarifa_id__get"];
        /**
         * Edita uma tarifa
         * @description Atualiza valor, prazo ou faixas de uma tarifa. Não altera cotações já geradas.
         */
        put: operations["tarifas_editar_tarifa_tarifas__int_tarifa_id__put"];
        post?: never;
        /**
         * Remove uma tarifa
         * @description Remove uma tarifa. Cotações já geradas guardam seus valores e não são afetadas.
         */
        delete: operations["tarifas_remover_tarifa_tarifas__int_tarifa_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AtualizarStatusSchema
         * @description Corpo da atualização de status; a máquina de estados valida a transição.
         */
        AtualizarStatusSchema: {
            /**
             * Observacao
             * @description Observação opcional para o histórico
             * @default null
             */
            observacao: string | null;
            /**
             * Status
             * @description Novo status: em_transito ou entregue
             */
            status: string;
        };
        /**
         * CotacaoSchema
         * @description Uma cotação: valor e prazo de frete em uma modalidade.
         */
        CotacaoSchema: {
            /**
             * Contratada
             * @description True se esta é a cotação contratada do pedido
             */
            contratada: boolean;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /**
             * Data Prometida
             * Format: date
             */
            data_prometida: string;
            /** Id */
            id: number;
            /** Modalidade Codigo */
            modalidade_codigo: string;
            /** Modalidade Nome */
            modalidade_nome: string;
            /** Pedido Id */
            pedido_id: number;
            /** Prazo Dias Uteis */
            prazo_dias_uteis: number;
            /**
             * Valor
             * @description Valor do frete em reais
             */
            valor: number;
        };
        /**
         * ErroSchema
         * @description Corpo devolvido em qualquer erro (400, 404, 409, 502), com mensagem em português.
         */
        ErroSchema: {
            /**
             * Mensagem
             * @description Descrição do erro
             */
            mensagem: string;
        };
        /**
         * FreteRegiaoSchema
         * @description Frete médio contratado em uma região do Brasil.
         */
        FreteRegiaoSchema: {
            /** Frete Medio */
            frete_medio: number;
            /**
             * Quantidade
             * @description Pedidos com frete contratado na região
             */
            quantidade: number;
            /** Regiao */
            regiao: string;
        };
        /**
         * ImportacaoSchema
         * @description Resultado da importação de pedidos da DummyJSON.
         */
        ImportacaoSchema: {
            /**
             * Ignorados
             * @description Pedidos que já existiam (importação idempotente)
             */
            ignorados: number;
            /**
             * Importados
             * @description Pedidos novos gravados
             */
            importados: number;
            /** Mensagem */
            mensagem: string;
        };
        /**
         * ItemPedidoSchema
         * @description Produto de um pedido com dados físicos (peso em kg, dimensões em cm).
         */
        ItemPedidoSchema: {
            /** Altura */
            altura: number;
            /** Id */
            id: number;
            /** Largura */
            largura: number;
            /** Peso */
            peso: number;
            /** Preco Unitario */
            preco_unitario: number;
            /** Produto Id Externo */
            produto_id_externo: number;
            /** Profundidade */
            profundidade: number;
            /** Quantidade */
            quantidade: number;
            /** Sku */
            sku: string | null;
            /** Titulo */
            titulo: string;
        };
        /**
         * ListaCotacoesSchema
         * @description Cotações geradas para um pedido (uma por modalidade ativa).
         */
        ListaCotacoesSchema: {
            /** Cotacoes */
            cotacoes: components["schemas"]["CotacaoSchema"][];
        };
        /**
         * ListaModalidadesSchema
         * @description Modalidades cadastradas.
         */
        ListaModalidadesSchema: {
            /** Modalidades */
            modalidades: components["schemas"]["ModalidadeSchema"][];
        };
        /**
         * ListaPedidosSchema
         * @description Página de pedidos com metadados de paginação.
         */
        ListaPedidosSchema: {
            /** Pagina */
            pagina: number;
            /** Pedidos */
            pedidos: components["schemas"]["PedidoResumoSchema"][];
            /** Por Pagina */
            por_pagina: number;
            /** Total */
            total: number;
            /** Total Paginas */
            total_paginas: number;
        };
        /**
         * ListaTarifasSchema
         * @description Tabela completa de tarifas, ordenada por peso e distância.
         */
        ListaTarifasSchema: {
            /** Tarifas */
            tarifas: components["schemas"]["TarifaSchema"][];
        };
        /**
         * ModalidadeSchema
         * @description Modalidade de frete e seus ajustes sobre a tarifa base.
         */
        ModalidadeSchema: {
            /** Ajuste Prazo Dias */
            ajuste_prazo_dias: number;
            /** Ativa */
            ativa: boolean;
            /** Codigo */
            codigo: string;
            /** Id */
            id: number;
            /** Multiplicador Valor */
            multiplicador_valor: number;
            /** Nome */
            nome: string;
            /** Prazo Maximo Dias */
            prazo_maximo_dias: number | null;
            /** Prazo Minimo Dias */
            prazo_minimo_dias: number;
        };
        /**
         * MovimentacaoSchema
         * @description Uma mudança de status na linha do tempo do pedido.
         */
        MovimentacaoSchema: {
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** De Status */
            de_status: string | null;
            /** Id */
            id: number;
            /** Observacao */
            observacao: string | null;
            /** Para Status */
            para_status: string;
        };
        /**
         * PainelSchema
         * @description Métricas consolidadas da operação.
         */
        PainelSchema: {
            /**
             * Atrasados
             * @description Pedidos com data prometida vencida e não entregues/cancelados
             */
            atrasados: number;
            /**
             * Contagem Por Status
             * @description Quantidade de pedidos em cada status
             */
            contagem_por_status: {
                [key: string]: number;
            };
            /**
             * Frete Medio Geral
             * @description Média dos fretes contratados, em reais
             * @default null
             */
            frete_medio_geral: number | null;
            /** Frete Medio Por Regiao */
            frete_medio_por_regiao: components["schemas"]["FreteRegiaoSchema"][];
            /**
             * Prazo Medio Contratado
             * @description Média de dias úteis das cotações contratadas
             * @default null
             */
            prazo_medio_contratado: number | null;
            /** Total Pedidos */
            total_pedidos: number;
        };
        /**
         * PedidoDetalheSchema
         * @description Pedido completo: cliente, endereço, pesos, itens, cotações e movimentações.
         */
        PedidoDetalheSchema: {
            /**
             * Atrasado
             * @description data_prometida já passou e o pedido não foi entregue nem cancelado
             */
            atrasado: boolean;
            /**
             * Atualizado Em
             * Format: date-time
             */
            atualizado_em: string;
            /** Bairro */
            bairro: string;
            /** Cep */
            cep: string;
            /** Cidade */
            cidade: string;
            /** Cliente Email */
            cliente_email: string;
            /** Cliente Nome */
            cliente_nome: string;
            /** Cotacao Contratada Id */
            cotacao_contratada_id: number | null;
            /** Cotacoes */
            cotacoes: components["schemas"]["CotacaoSchema"][];
            /** Data Prometida */
            data_prometida: string | null;
            /** Distancia Km */
            distancia_km: number;
            /** Endereco Verificado */
            endereco_verificado: boolean;
            /** Id */
            id: number;
            /** Id Externo */
            id_externo: number;
            /**
             * Importado Em
             * Format: date-time
             */
            importado_em: string;
            /** Itens */
            itens: components["schemas"]["ItemPedidoSchema"][];
            /** Latitude */
            latitude: number | null;
            /** Logradouro */
            logradouro: string;
            /** Longitude */
            longitude: number | null;
            /** Movimentacoes */
            movimentacoes: components["schemas"]["MovimentacaoSchema"][];
            /** Numero */
            numero: string;
            /** Peso Cobrado */
            peso_cobrado: number;
            /** Peso Cubado */
            peso_cubado: number;
            /** Peso Real */
            peso_real: number;
            /**
             * Quantidade Itens
             * @description Soma das quantidades dos itens
             */
            quantidade_itens: number;
            /** Status */
            status: string;
            /** Uf */
            uf: string;
            /**
             * Valor Frete
             * @description Valor da cotação contratada, se houver
             * @default null
             */
            valor_frete: number | null;
            /** Valor Mercadoria */
            valor_mercadoria: number;
        };
        /**
         * PedidoResumoSchema
         * @description Dados essenciais de um pedido, usados na fila.
         */
        PedidoResumoSchema: {
            /**
             * Atrasado
             * @description data_prometida já passou e o pedido não foi entregue nem cancelado
             */
            atrasado: boolean;
            /** Cidade */
            cidade: string;
            /** Cliente Nome */
            cliente_nome: string;
            /** Data Prometida */
            data_prometida: string | null;
            /** Distancia Km */
            distancia_km: number;
            /** Id */
            id: number;
            /** Id Externo */
            id_externo: number;
            /**
             * Importado Em
             * Format: date-time
             */
            importado_em: string;
            /** Peso Cobrado */
            peso_cobrado: number;
            /**
             * Quantidade Itens
             * @description Soma das quantidades dos itens
             */
            quantidade_itens: number;
            /** Status */
            status: string;
            /** Uf */
            uf: string;
            /**
             * Valor Frete
             * @description Valor da cotação contratada, se houver
             * @default null
             */
            valor_frete: number | null;
        };
        /**
         * TarifaEntradaSchema
         * @description Dados para criar ou editar uma tarifa (célula peso × distância da tabela).
         */
        TarifaEntradaSchema: {
            /**
             * Distancia Max Km
             * @description Limite superior da faixa de distância, em km
             */
            distancia_max_km: number;
            /**
             * Peso Max Kg
             * @description Limite superior da faixa de peso, em kg
             */
            peso_max_kg: number;
            /**
             * Prazo Dias Uteis
             * @description Prazo base em dias úteis
             */
            prazo_dias_uteis: number;
            /**
             * Valor
             * @description Valor base do frete em reais
             */
            valor: number;
        };
        /**
         * TarifaRemovidaSchema
         * @description Confirmação de remoção de tarifa.
         */
        TarifaRemovidaSchema: {
            /** Id */
            id: number;
            /** Mensagem */
            mensagem: string;
        };
        /**
         * TarifaSchema
         * @description Tarifa gravada, com id.
         */
        TarifaSchema: {
            /**
             * Distancia Max Km
             * @description Limite superior da faixa de distância, em km
             */
            distancia_max_km: number;
            /** Id */
            id: number;
            /**
             * Peso Max Kg
             * @description Limite superior da faixa de peso, em kg
             */
            peso_max_kg: number;
            /**
             * Prazo Dias Uteis
             * @description Prazo base em dias úteis
             */
            prazo_dias_uteis: number;
            /**
             * Valor
             * @description Valor base do frete em reais
             */
            valor: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    inicio__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
        };
    };
    cotacoes_contratar_cotacoes__int_cotacao_id__contratar_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da cotação */
                cotacao_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDetalheSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    tarifas_listar_modalidades_modalidades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaModalidadesSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
        };
    };
    painel_painel_painel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PainelSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
        };
    };
    pedidos_listar_pedidos_get: {
        parameters: {
            query?: {
                /** @description recebido, cotado, contratado, em_transito, entregue ou cancelado */
                status?: string | null;
                /** @description Sigla do estado de destino, ex.: SP */
                uf?: string | null;
                /** @description Busca por nome do cliente, cidade ou id externo */
                q?: string | null;
                /** @description Número da página, a partir de 1 */
                pagina?: number;
                /** @description Itens por página */
                por_pagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaPedidosSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    pedidos_importar_pedidos_importar_post: {
        parameters: {
            query?: {
                /** @description Máximo de pedidos novos a importar nesta chamada */
                quantidade?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportacaoSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    pedidos_detalhar_pedidos__int_pedido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do pedido na Docas */
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDetalheSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    pedidos_cancelar_pedidos__int_pedido_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do pedido na Docas */
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDetalheSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    pedidos_cotar_pedidos__int_pedido_id__cotacoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do pedido na Docas */
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaCotacoesSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    pedidos_atualizar_status_pedidos__int_pedido_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do pedido na Docas */
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarStatusSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDetalheSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    tarifas_listar_tarifas_tarifas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaTarifasSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
        };
    };
    tarifas_criar_tarifa_tarifas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarifaEntradaSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarifaSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    tarifas_detalhar_tarifa_tarifas__int_tarifa_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da tarifa */
                tarifa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarifaSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    tarifas_editar_tarifa_tarifas__int_tarifa_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da tarifa */
                tarifa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarifaEntradaSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarifaSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
    tarifas_remover_tarifa_tarifas__int_tarifa_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da tarifa */
                tarifa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarifaRemovidaSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroSchema"];
                };
            };
        };
    };
}
